UK_BUSINESS = 'UK_BUSINESS'
UK_CONSUMER = 'UK_CONSUMER'
DEVELOPING_COUNTRY_COMPANY = 'DEVELOPING_COUNTRY_COMPANY'

INCREASE = 'INCREASE'
DECREASE = 'DECREASE'
QUOTA_CHANGE = 'QUOTA_CHANGE'
OTHER = 'OTHER'

ACTUAL = 'ACTUAL'
EXPECTED = 'EXPECTED'

GENERALISED_SYSTEM_OF_PERFERENCE_COUNTRIES = (
  'Afghanistan',
  'Angola',
  'Armenia',
  'Bangladesh',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Burkina Faso',
  'Burma',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Comoros',
  'Congo',
  'Cook Islands',
  'Djibouti',
  'East Timor',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Ethiopia',
  'Gambia (The)',
  'Georgia',
  'Ghana',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'India',
  'Indonesia',
  'Ivory Coast',
  'Jordan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kyrgyzstan',
  'Laos',
  'Lesotho',
  'Liberia',
  'Madagascar',
  'Malawi',
  'Mali',
  'Mauritania',
  'Micronesia',
  'Moldova',
  'Mongolia',
  'Morocco',
  'Mozambique',
  'Nauru',
  'Nepal',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Occupied Palestinian Territories',
  'Pakistan',
  'Papua New Guinea',
  'Philippines',
  'Rwanda',
  'Samoa',
  'Sao Tome and Principe',
  'Senegal',
  'Sierra Leone',
  'Solomon Islands',
  'Somalia',
  'South Sudan',
  'Sri Lanka',
  'Sudan',
  'Swaziland',
  'Syria',
  'Tajikistan',
  'Tanzania',
  'Togo',
  'Tonga',
  'Tunisia',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'Uzbekistan',
  'Vanuatu',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
)
